gateway:
  admin:
    enabled: true
    type: ClusterIP
    clusterIP: None
    
    # Needed for Kong Manager on HTTP
    http:
      enabled: true

  # Custom Plugin
  plugins:
    configMaps:
    - name: logger
      pluginName: logger
    - name: myheader
      pluginName: myheader
    - name: loadtest
      pluginName: loadtest
    - name: jwtchecker
      pluginName: jwtchecker
      
    # Custom ACL plugin
    - name: "acl-jwt-custom"
      pluginName: "acl-jwt-custom"